services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  backend:
    build: ./be
    expose:
      - "8000"  # Only expose on internal network, not bind to host port
    env_file:
      - ./be/.env
    environment:
      - QDRANT_HOST=qdrant
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False  # Disable debug in production
      - FRONTEND_HOST=13.238.233.29  # Your EC2 public IP
    volumes:
      - ./be:/app
    depends_on:
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./fe
    expose:
      - "3000"  # Only expose on internal network, not bind to host port
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped 

  qdrant:
    image: qdrant/qdrant:v1.9.1   
    container_name: qdrant
    ports:
      - "127.0.0.1:6333:6333"  # Only bind to localhost, don't expose database
    volumes:
      - ./qdrant_data:/qdrant/storage   # data persistence
    healthcheck:
      test: ["CMD-SHELL", "pidof qdrant || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s