services:
  backend:
    build: ./be
    ports:
      - "8000:8000"
    env_file:
      - ./be/.env
    environment:
      - QDRANT_HOST=qdrant
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
    volumes:
      - ./be:/app
    depends_on:
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./fe
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped 

  qdrant:
    image: qdrant/qdrant:v1.9.1   
    container_name: qdrant
    ports:
      - "6333:6333"               # default API port
    volumes:
      - ./qdrant_data:/qdrant/storage   # data persistence
    healthcheck:
      test: ["CMD-SHELL", "pidof qdrant || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s