services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build: ./be
    expose:
      - "8000"  # Only expose on internal network, not bind to host port
    env_file:
      - ./be/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False  # Disable debug in production
      - FRONTEND_HOST=13.238.233.29  # Your EC2 public IP
    volumes:
      - ./be:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: 
      context: ./fe
    expose:
      - "3000"  # Only expose on internal network, not bind to host port
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

